### ISSUE TITLE
My own number

### ISSUE THREAD

**Issue by morglen** [Emilien-B/receive-sms#1]
Hi. How can I use my own number and read texts?

**Comment by Emilien-B** [comment]
Hi,
Sorry, you can't use your own number.
You have to use one of [these phone numbers](https://github.com/Emilien-B/receive-sms#the-phone-numbers-you-can-use).
Thank you for you interest.

**Comment by morglen** [comment]
What's the point of this lib then?

**Comment by Emilien-B** [comment]
My lib allows you to get sms sent to specific phone numbers. For example, you can use it to bypass 2fa or to control something with sms (like polls or IoT).
You may have thought you had to own the phone number to use it. These are public phone numbers, everyone can read messages for free.
